; Managed by Civ 3 | C3X Modern Editor
; Mode: scenario

minimum_city_separation           = 6
production_perfume                = ["Semiconductor Foundry": 200%, "Harbor": 200%]
building_prereqs_for_units        = ["Factory": "Modern Armor", "Space Elevator": "Transorbital Carrier"]
buildings_generating_resources    = ["Spartan Camp": "Mercenaries", "Spartan Camp": "Mercenaries", "Spartan Camp": "Mercenaries", "Venetian Glassworks": "Glassware", "Venetian Glassworks": "Glassware", "Venetian Glassworks": "Glassware", "Singapore Wafer Foundry": "Silicon Wafers", "Singapore Wafer Foundry": "Silicon Wafers", "Singapore Wafer Foundry": "Silicon Wafers", "St. Peter's Basilica": "Religious Relics", "St. Peter's Basilica": "Religious Relics", "St. Peter's Basilica": "Religious Relics", "Semiconductor Foundry": "Silicon Wafers", "Semiconductor Foundry": "Silicon Wafers", "Hollywood": "Films", "Hollywood": "Films", "Hollywood": "Films", "Broadway": "Music", "Broadway": "Music", "Broadway": "Music"]
city_work_radius                  = 4
allow_unload_from_army            = true
enable_districts                  = true
enable_neighborhood_districts     = true
enable_wonder_districts           = true
enable_distribution_hub_districts = true
enable_aerodrome_districts        = true
enable_port_districts             = true
enable_bridge_districts           = true
enable_canal_districts            = true
enable_central_rail_hub_districts = true
enable_great_wall_districts       = true
