; Managed by Civ 3 | C3X Modern Editor
; Mode: scenario

ai_worker_requirement_percent                      = 300
minimum_city_separation                            = 6
production_perfume                                 = ["Semiconductor Foundry": 200%, "Harbor": 200%]
show_ai_city_location_desirability_if_settler      = true
building_prereqs_for_units                         = ["Factory": "Modern Armor", "Space Elevator": "Transorbital Carrier", "Autonomous Assembly Plant": "Autonomous Mech"]
buildings_generating_resources                     = ["Spartan Camp": "Mercenaries", "Spartan Camp": "Mercenaries", "Spartan Camp": "Mercenaries", "Venetian Glassworks": "Glassware", "Venetian Glassworks": "Glassware", "Venetian Glassworks": "Glassware", "Singapore Wafer Foundry": "Silicon Wafers", "Singapore Wafer Foundry": "Silicon Wafers", "Singapore Wafer Foundry": "Silicon Wafers", "St. Peter's Basilica": "Religious Relics", "St. Peter's Basilica": "Religious Relics", "St. Peter's Basilica": "Religious Relics", "Semiconductor Foundry": "Silicon Wafers", "Semiconductor Foundry": "Silicon Wafers", "Hollywood": "Films", "Hollywood": "Films", "Hollywood": "Films", "Broadway": "Music", "Broadway": "Music", "Broadway": "Music", "Nassau Letters of Marque Office": "Rum", "Nassau Letters of Marque Office": "Rum", "Nassau Letters of Marque Office": "Rum"]
city_work_radius                                   = 4
auto_zoom_city_screen_for_large_work_areas         = false
allow_unload_from_army                             = true
allow_extraterritorial_colonies                    = true
tiles_per_non_luxury_resource                      = 20
enable_custom_animations                           = true
day_night_cycle_mode                               = timer
seasonal_cycle_mode                                = on-day-night-hour
enable_natural_wonders                             = true
add_natural_wonders_to_scenarios_if_none           = true
enable_districts                                   = true
enable_neighborhood_districts                      = true
enable_wonder_districts                            = true
enable_distribution_hub_districts                  = true
enable_aerodrome_districts                         = true
enable_port_districts                              = true
enable_bridge_districts                            = true
enable_canal_districts                             = true
enable_central_rail_hub_districts                  = true
enable_great_wall_districts                        = true
central_rail_hub_distribution_food_bonus_percent   = 100
central_rail_hub_distribution_shield_bonus_percent = 0
disable_great_wall_city_defense_bonus              = true
